name: ShadowX PHP Proxy
on: [workflow_dispatch]

jobs:
  proxy:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PHP
        run: |
          sudo apt update
          sudo apt install -y php-cli php-curl php-mbstring

      - name: Start PHP Server
        run: |
          # فایل‌ها از قبل توی phprxyv2 هستن
          cd phprxyv2
          nohup php -S 0.0.0.0:8888 > /tmp/php.log 2>&1 &
          sleep 3
          
          # چک کن PHP بالا اومده
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8888/
          echo ""

      - name: Setup Ngrok
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com bookworm main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok http 8888 --request-header-add="ngrok-skip-browser-warning:true" > /tmp/ngrok.log 2>&1 &
          sleep 10

      - name: Show URL
        run: |
          TUNNEL_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "========================================="
          echo "🌐 ShadowX Proxy: $TUNNEL_URL"
          echo "========================================="
          sleep 21600
